/// Flutter icons Allicons
/// Copyright (C) 2021 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  Allicons
///      fonts:
///       - asset: fonts/Allicons.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class Allicons {
  Allicons._();

  static const _kFontFam = 'Allicons';
  static const String _kFontPkg = null;

  static const IconData noun_groups_3874047 = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData noun_watch_3874055 = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData like = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData instagram_reels = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData video = IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData noun_photo_3874106 = IconData(0xe809, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData noun_share_3943829 = IconData(0xe80a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
