/// Flutter icons Twoicons
/// Copyright (C) 2021 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  Twoicons
///      fonts:
///       - asset: fonts/Twoicons.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class Twoicons {
  Twoicons._();

  static const _kFontFam = 'Twoicons';
  static const String _kFontPkg = null;

  static const IconData menu = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData user_group = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
